#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
opentofu_dir="${OPENTOFU_DIR:-${repo_root}/../opentofu}"
manifest="${SYNC_MANIFEST:-${repo_root}/sync/opentofu-files.tsv}"

if [[ ! -d "${opentofu_dir}/.git" ]]; then
  echo "OpenTofu checkout not found at ${opentofu_dir}" >&2
  echo "Set OPENTOFU_DIR to a local OpenTofu checkout." >&2
  exit 1
fi

if [[ ! -f "${manifest}" ]]; then
  echo "sync manifest not found: ${manifest}" >&2
  exit 1
fi

upstream_commit="$(git -C "${opentofu_dir}" rev-parse HEAD)"
upstream_status="$(git -C "${opentofu_dir}" status --short)"
if [[ -n "${upstream_status}" && "${ALLOW_DIRTY_OPENTOFU:-}" != "1" ]]; then
  echo "OpenTofu checkout has local changes; refusing to sync." >&2
  echo "${upstream_status}" >&2
  echo "Set ALLOW_DIRTY_OPENTOFU=1 only for deliberate local experiments." >&2
  exit 1
fi

today="$(date -u +%F)"
copied_count=0
report_file="$(mktemp)"
trap 'rm -f "${report_file}"' EXIT

{
  echo "Generated by scripts/sync-opentofu.sh on ${today}."
  echo
  echo "- Upstream checkout: ${opentofu_dir}"
  echo "- Upstream commit inspected: ${upstream_commit}"
  echo "- Sync manifest: sync/opentofu-files.tsv"
  echo
  echo "| OpenTofu source path | tfconfig destination path | Notes |"
  echo "| --- | --- | --- |"
} >"${report_file}"

while IFS=$'\t' read -r source_path dest_path notes _extra; do
  if [[ -z "${source_path// }" || "${source_path}" == \#* ]]; then
    continue
  fi
  if [[ -z "${dest_path// }" ]]; then
    echo "missing destination path for ${source_path}" >&2
    exit 1
  fi
  if [[ "${source_path}" == /* || "${source_path}" == *..* || "${dest_path}" == /* || "${dest_path}" == *..* ]]; then
    echo "unsafe sync path: ${source_path} -> ${dest_path}" >&2
    exit 1
  fi

  source="${opentofu_dir}/${source_path}"
  dest="${repo_root}/${dest_path}"
  if [[ ! -f "${source}" ]]; then
    echo "source file not found: ${source_path}" >&2
    exit 1
  fi

  mkdir -p "$(dirname "${dest}")"
  cp "${source}" "${dest}"

  if [[ "${dest_path}" == *.go ]] && ! grep -q "SPDX-License-Identifier: MPL-2.0" "${dest}"; then
    echo "copied Go file lacks MPL-2.0 SPDX header: ${dest_path}" >&2
    exit 1
  fi

  copied_count=$((copied_count + 1))
  echo "| \`${source_path}\` | \`${dest_path}\` | ${notes:-copied from OpenTofu} |" >>"${report_file}"
done <"${manifest}"

if [[ "${copied_count}" -eq 0 ]]; then
  cat >>"${report_file}" <<'EOF'

No active file mappings are configured yet.
EOF
fi

tmp_upstream="$(mktemp)"
awk -v report="${report_file}" '
  BEGIN {
    while ((getline line < report) > 0) {
      replacement = replacement line "\n"
    }
    close(report)
  }
  /<!-- sync:begin -->/ {
    print
    printf "%s", replacement
    in_block = 1
    next
  }
  /<!-- sync:end -->/ {
    in_block = 0
    print
    next
  }
  !in_block { print }
' "${repo_root}/UPSTREAM.md" >"${tmp_upstream}"
mv "${tmp_upstream}" "${repo_root}/UPSTREAM.md"

echo "Synced ${copied_count} OpenTofu file(s) from ${upstream_commit}."
